### ISSUE TITLE
love it!

### ISSUE THREAD

**Issue by BBC-Esq** [gkamradt/ChunkViz#2]
Love this program!  Checked out your website and it's interactive and updates the chunking visualizations...I'm want to incorporate a feature in my program [https://github.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio](https://github.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio) to give user's the option to view how a sample document would be chunked...that way they can make a decision on the chunk size and overlap settings in my program.

Unfortunately, I don't know javascript.  Any guidance on how to convert this to pure Python?

**Comment by gkamradt** [comment]
For the backend you can check out llama index and langchains splitters. They have a bunch.

Then it's a matter of recreating the full text from the output chunks. I would have done pure python but I liked the auto-update nature of react too much
