### ISSUE TITLE
Please give running instructions in Readme.md

### ISSUE THREAD

**Issue by thealy** [gkamradt/ChunkViz#3]
Please give instructions how to run the app from the code in the repository as the links to the demo point to a domain with an expired certificate (and railway.app is commonly blocked).

**Comment by gkamradt** [comment]
No problem! Just updated the read me with how to do it

Let me know if you have problems

**Comment by thealy** [comment]
Thanks very much!

**Comment by gkamradt** [comment]
np, can you confirm you got it running locally so I can close this out?

**Comment by thealy** [comment]
Yes, will do tomorrow morning EST.
